package com.smashwinscounter.smashwinscounter;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
public class Win {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Auto-generated by Supabase

    @Enumerated(EnumType.STRING)
    private Player winningPlayer;
    @Enumerated(EnumType.STRING)
    private Character winningCharacter;
    @Enumerated(EnumType.STRING)
    private Player losingPlayer;
    @Enumerated(EnumType.STRING)
    private Character losingCharacter;
    @CreationTimestamp
    private LocalDateTime winTime;

    // No-args constructor necessitated by JPA
    public Win() {}

    public Win(Player winningPlayer, Character winningCharacter, Player losingPlayer, Character losingCharacter) {
        this.winningPlayer = winningPlayer;
        this.winningCharacter = winningCharacter;
        this.losingPlayer = losingPlayer;
        this.losingCharacter = losingCharacter;
        this.winTime = LocalDateTime.now();
    }

    public long getId() {return id;}

    public Player getWinningPlayer() {return winningPlayer;}
    public void  setWinningPlayer(Player winningPlayer) {this.winningPlayer = winningPlayer;}

    public Character getWinningCharacter() {return winningCharacter;}
    public void setWinningCharacter(Character winningCharacter) {this.winningCharacter = winningCharacter;}

    public Player getLosingPlayer() {return losingPlayer;}
    public void setLosingPlayer(Player losingPlayer) {this.losingPlayer = losingPlayer;}

    public Character getLosingCharacter() {return losingCharacter;}
    public void setLosingCharacter(Character losingCharacter) {this.losingCharacter = losingCharacter;}
}
